on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/my_action/
        with:
          who-to-greet: "Ladislas"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: |
          echo "env variable: ${{ env.action_state }}"
        shell: bash
      - run: |
          echo "other env variable: $OTHER_ACTION_STATE"
        shell: bash
      - run: |
          echo "other env variable: ${{ env.OTHER_ACTION_STATE }}"
        shell: bash
